#!/bin/bash

profile=$(echo "buildserver:$1")
eselect profile set $profile

# https://bugs.gentoo.org/680456
export FEATURES="-ipc-sandbox -mount-sandbox -network-sandbox -pid-sandbox"
emerge -DN --buildpkg --usepkg @world
